### PR TITLE
Fixes #36

### LINKED ISSUE #36: Complete information on selected studies in Studies, DDI and Projects sheet
@PavelBal

Please complete information for the following studies in the Sheets `Studies`, `DDI` and `Projects`

| ID   | Study               | Reference                                 |
| ---- | ------------------- | ----------------------------------------- |
| 6010 | Yasui-Furukori 2004 | https://pubmed.ncbi.nlm.nih.gov/15025747/ |
| 6011 | Yasui-Furukori 2004 | https://pubmed.ncbi.nlm.nih.gov/15025747/ |
| 6020 | Cho 2002            | https://pubmed.ncbi.nlm.nih.gov/11966672/ |
| 6021 | Cho 2002            | https://pubmed.ncbi.nlm.nih.gov/11966672/ |
| 6030 | Yao 2003            | https://pubmed.ncbi.nlm.nih.gov/12695344/ |
| 6031 | Yao 2003            | https://pubmed.ncbi.nlm.nih.gov/12695344/ |
| 6032 | Yao 2003            | https://pubmed.ncbi.nlm.nih.gov/12695344/ |
| 6040 | Yu 2001             | https://pubmed.ncbi.nlm.nih.gov/11309556/ |
| 6050 | Granfors 2005       | https://pubmed.ncbi.nlm.nih.gov/16198659/ |
| 6060 | Jeppesen 1996       | https://pubmed.ncbi.nlm.nih.gov/8807660/  |
| 6061 | Culm-Merdek 2005    | https://pubmed.ncbi.nlm.nih.gov/16236038/ |
| 6070 | Granfors 2004       | https://pubmed.ncbi.nlm.nih.gov/14998432/ |
| 6080 | Joeres 1987         | https://pubmed.ncbi.nlm.nih.gov/3628469/  |
| 6090 | Momo 2010           | https://pubmed.ncbi.nlm.nih.gov/19789372/ |
| 6100 | Kusumoto 2001       | https://pubmed.ncbi.nlm.nih.gov/11240973/ |
| 6110 | Balogh 1995         | https://pubmed.ncbi.nlm.nih.gov/7589032/  |

### PR DESCRIPTION
**Pull request by PavelBal**
Added information for data sets 6010, 6011, 6020, 6021, 6030, 6031, 6032, 6040, 6050, 6060, 6061, 6070, 6080, 6090, 6100, 6110
Added projects for data sets 6010, 6011, 6020, 6021, 6030, 6031, 6032, 6040, 6050, 6060, 6061, 6070, 6080, 6090, 6100, 6110
Added PK-profile data sets 11028, 11050, 11051, 11052, 11048, 11049, 11026, 11027, 10027, 14001, 14002, 14003, 14004, 14005, 14006, 13016, 13017, 14007, 14008, 13018, 13001, 14009, 14010, 15000, 15001, 15002, 15003, 10005

### CODE REVIEW

**Comment by sfrechen** [comment]
@PavelBal 
Could you resolve the conflicts? I assume you need to grab a fresh copy of the xls and copy your new data in.

**Comment by PavelBal** [comment]
@sfrechen Conflicts resolved (re-added the data sets to excel based on current master branch).

the exported DDI.csv has comma as separator. If you require `;` (I would ask "why?"), please be so kind and export the sheet to csv on your machine. I cannot change my systems settings.

Please merge asap, I will then make a new PR adding CT-profile data for model evaluation.

**Comment by Yuri05** [comment]
>If you require ; (I would ask "why?"), please be so kind and export the sheet to csv on your machine. I cannot change my systems settings.

With the next version of RE only comma will be accepted as column separator, so all good here

**Comment by sfrechen** [comment]
@PavelBal 
Your excel file seems to be corrupt and link to your local files:
image

**Comment by PavelBal** [comment]
wtf is this, what did excel do there??

**Comment by PavelBal** [comment]
Fixed..

**Comment by sfrechen** [comment]
@PavelBal :
Still not clean. Contains duplicates, e.g.:
image

**Comment by sfrechen** [comment]
And would be nice to keep color coding, example where it is overwritten:
image

**Comment by sfrechen** [comment]
@PavelBal 
I have cleaned it up. Please take a fresh copy and insert your lines ("as text") at the end of each sheet. Then pull down the formulas foe the "grayish" columns which are read from studies sheet.

**Comment by PavelBal** [comment]
@sfrechen Most of the duplicates were because DDI ratios were stored as separate IDs. I now consolidated the data, with following IDs being added:

6110
11048
11049
11026
11027
14005
14006
13016
13017
14001
14002
14003
14004
14007
14008
14009
14010
13018
13001
15000
15001
15002
15003
11028
11050
11051
11052
10027
10005


BTW: the new script works great, thanks ;)

**Comment by PavelBal** [comment]
@sfrechen Did you have a chance to check the changes?

**Comment by Yuri05** [comment]
>I think we can close this PR then.

"close"="merge" or "close"="close without merging"?

**Pull request closed without merging**
