### PR TITLE
Added fluconazole DDI data

### PR DESCRIPTION
**Pull request by ErikssonJ**

### CODE REVIEW

**Comment by sfrechen** [comment]
@ErikssonJ 
Thank you for your PR.
Usually, we use (if availale) the "exact" times and not the "scanned" time for ct profiles, i.e. we would correct 1.01223 to 1 hour. Just saw that you have multiple values that seem to be the ones from the scanning procedure...

**Comment by ErikssonJ** [comment]
@sfrechen 
I have now corrected the time inputs for fluconazole where information was available in the publications.

**Comment by sfrechen** [comment]
@ErikssonJ 
Thanks. Plese re-assess ID 1366 to 1370 and 1385. Even if not mentioned in the paper, I think we can guess the times (at least for the 1366 to 1370).

One more thing in the DDI sheet: I think I remember that the column Mechanism should not contain blanks.

Suggestion: replace all entries with "Competitive_Inhibition" and your new term "non-competetive inhibition" by "Reversible_Inhibition". I think merging the two entities in the plots later makes sense.

**Comment by ErikssonJ** [comment]
@sfrechen 
I forgot to comment that I made a new commit, don't know if you got notified or not. I replaced the entries in the DDI sheet to Reversible_Inhibition as you suggested (and updated timepoints for fluconazole).

**Pull request merged**
