### PR TITLE
Cyp1a2 cyp2c19

### PR DESCRIPTION
**Pull request by PavelBal**

### CODE REVIEW

**Comment by StephanSchaller** [comment]
@Yuri05 , can you review this? :-)

**Comment by Yuri05** [comment]
@StephanSchaller No. @AndreDlm or @sfrechen could do.

**Comment by AndreDlm** [comment]
I don't have an option for formal review. The `csv` file looks fine to me, but a few entries are missing (e.g. PubMed link)

**Comment by StephanSchaller** [comment]
@Yuri05 @AndreDlm, yes, we definitely need a workflow description of how to get models integrated into the release process with some formal requirements for people assigned as reviewers (which technically several people could be assigned as in the future).

**Comment by PavelBal** [comment]
So what are the next steps to complete this PR?

**Comment by Yuri05** [comment]
ok, merging.
@AndreDlm Can you please create the issue(s) for "few entries are missing (e.g. PubMed link)"? This can be fixed later than.

**Pull request merged**
